### ISSUE TITLE
Docker rootfs build

### ISSUE THREAD

**Issue by srbala** [rocky-linux/distrobuild#5]
Team,

Any plans to build cloud/docker rootfs files?

**Comment by NeilHanlon** [comment]
Hi @srbala  - these will be produced as part of the artifacts generated in our Compose run for the final GA build.

Best,
Neil

**Comment by mstg** [comment]
Test AMIs and x86_64 Docker image are now available.

*PS: Please only use the distrobuild issue tracker related to issues with the tool itself. Distro related bugs/requests should be filed at [Rocky Linux Bugzilla](https://bugs.rockylinux.org)*
